import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { AppWrapper } from "@/context";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Cook-It",
  description: "Generated by F12",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppWrapper>

          <Navbar />
          <main className="flex-grow">
            {children}
            <Toaster  richColors position="top-right"></Toaster>
          </main>
          <Footer/>

        </AppWrapper>

      </body>
    </html>
  );
}


